# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts --no-audit --no-fund

# Copy source
COPY . .

# Build the project
RUN npm run build

# Use smaller runtime image if desired (still node:lts-alpine)

# Entry point
ENTRYPOINT ["node", "dist/index.js"]
